version: "3.8"

networks:
  default:
    name: loki

x-deploy: &default-deploy
  resources:
    limits:
      memory: 200M

x-logging:
  &common_logging
  driver: "json-file"
  options:
    tag: "{{.ImageName}}|{{.ContainerName}}"
    max-size: "10M"
    max-file: "10"

services:
  app_python:
    image: cogbonna/app_python_image
    ports:
      - "5000:5000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:5000/ || exit 1",
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
    deploy: *default-deploy
    logging: *common_logging
  
  app_javascript:
    image: cogbonna/app_javascript_image
    ports:
      - "5001:5001"  
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:5001/ || exit 1",
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
    deploy: *default-deploy
    logging: *common_logging

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"  
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1",
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
    deploy: *default-deploy
    logging: *common_logging

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash -c ':> /dev/tcp/localhost/9080' || exit 1",
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
    deploy: *default-deploy
    logging: *common_logging
    ports:
      - "9080:9080"  

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1",
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
    deploy: *default-deploy
    logging: *common_logging

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1",
        ]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5
    deploy: *default-deploy
    logging: *common_logging