name: Python Flask Application

on:
  push:
    paths:
      - "app_python/**"
      - ".github/workflows/build-app-python.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: app_python

    - name: Run tests
      run: |
        python -m unittest app_python/tests/test_flask_app.py

    - name: Lint code with pylint
      run: |
        pip install pylint
        pylint app_python
      continue-on-error: true
  
  security:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # Download Snyk CLI if cache is not hit
    - name: Download Snyk CLI
      if: steps.cache-snyk.outputs.cache-hit != 'true'
      run: |
        curl -LO https://github.com/snyk/cli/releases/download/v1.1278.0/snyk-linux
        chmod +x snyk-linux

    # Run Snyk vulnerability scan
    - name: Run Snyk vulnerability scan
      run: ./snyk-linux test --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - security
      - build
    if: ${{ needs.security.result == 'success' && needs.build.result == 'success'}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: app_python_image
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/app_python_image:latest